-- Tabela para armazenar doações
CREATE TABLE IF NOT EXISTS `donations` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`amount` DECIMAL(10,2) NOT NULL,
`phone` VARCHAR(30) DEFAULT NULL,
`city` VARCHAR(100) DEFAULT NULL,
`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;